### ISSUE TITLE
Make: Edit-Post Page

### ISSUE THREAD

**Issue by Yourengab** [Mezzky/word-mogul#3]

**Comment by Mezzky** [comment]
@Yourengab jan lupa pull dari main dlu, sm sesuaiin codingnya

**Comment by Mezzky** [comment]
@Yourengab 
# Edit Post Page perlu Revisi yaitu:

## Tampilan Desktop
**Page bisa discroll atau beberapa content terpotong sedangkan di Design sudah pas tanpa Scrolling page**

![Desktop Edit-post Page](https://user-images.githubusercontent.com/91834119/185664239-dcd391be-902d-44b9-bfc2-2969ad27eeaf.png)
<hr>

### Tampilan yang Diinginkan

![Desktop Editor Page](https://user-images.githubusercontent.com/91834119/185664856-50d27614-a4c4-42ed-92b5-997b36888417.png)
<hr>

### Tampilan asli Wordmogul sebelumnya


![Wordmogul - write   publish your stuff on the web (1)](https://user-images.githubusercontent.com/91834119/185665239-8fa56c85-4089-4cac-8bba-1c6a51b5ec3e.png)


_Fix ini semua_ 
**di branch baru: fix-edit-post-desktop-view**
